name = "cluster-sync"
title = "MongoDB Cluster-to-Cluster Sync"

intersphinx = [ "https://docs.mongodb.com/manual/objects.inv" ]

toc_landing_pages = ["/quickstart",
                     "reference/reference",
                     "/release-notes/release-notes",
                     "/faq"
                    ]

[constants]
version = "1.0.0"
c2c-product-name = "Cluster-to-Cluster Sync"
c2c-full-product-name = "MongoDB Cluster-to-Cluster Sync"

[substitutions]
# string = "some other string"
